name: Publish to PyPI

on:
  push:
    tags:
      - "v*" # This triggers the workflow for tags starting with 'v'

jobs:
  build-and-publish:
    name: Build and publish to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/project/tunex
    permissions:
      contents: read # Required for checking out the code
      id-token: write

    steps:
      - name: Checkout source
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x" # Specify the version of Python you need

      - name: Install dependencies
        run: python -m pip install --upgrade build twine

      - name: Build source and wheel distributions
        run: python -m build

      - name: Check distributions
        run: twine check --strict dist/*

      - name: Publish distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
